export const apiEndpoints = {
  health: '/health',
  metaOptions: '/meta/options',
  nicknameSuggestions: '/auth/nickname-suggestions',
  profiles: '/auth/profiles',
  verify: '/auth/verify',
  me: '/profiles/me',
  places: '/places',
  placeDetail: (contentId: string) => `/places/${contentId}`,
  placeNearby: (contentId: string) => `/places/${contentId}/nearby`,
  weather: '/weather',
  chatSessions: '/chat/sessions',
  chatSessionDetail: (sessionId: string) => `/chat/sessions/${sessionId}`,
  chatSessionMessages: (sessionId: string) => `/chat/sessions/${sessionId}/messages`,
  chatSessionConfirm: (sessionId: string) => `/chat/sessions/${sessionId}/confirm`,
  currentCourse: '/date-courses/current',
  completeCoursePlace: (coursePlaceId: string) => `/date-courses/current/places/${coursePlaceId}/complete`,
  heartCoursePlace: (coursePlaceId: string) => `/date-courses/current/places/${coursePlaceId}/heart`,
  completeCurrentCourse: '/date-courses/current/complete',
  communityPosts: '/community/posts',
  communityPostDetail: (postId: string) => `/community/posts/${postId}`,
  communityPostLike: (postId: string) => `/community/posts/${postId}/like`,
  communityPostStart: (postId: string) => `/community/posts/${postId}/start`,
  rankingsMasters: '/rankings/masters',
  myDateCourses: '/profiles/me/date-courses',
  myDateCourseDetail: (courseId: string) => `/profiles/me/date-courses/${courseId}`,
  restartDateCourse: (courseId: string) => `/profiles/me/date-courses/${courseId}/restart`,
} as const
